services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:+DAdjZsQmsFtjQQAGpg9GPK9QisH6dzzVLuNJT6FLKE=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=closet_master
      - DB_USERNAME=root
      - DB_PASSWORD= miyayama3880
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: closet_master
      MYSQL_USER: user
      MYSQL_PASSWORD: miyayama3880
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
